# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
fr:
  languageCode: fr
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/fr

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en
  contentDir: content/en
  title: RECABEE
  params:
    description: Site description in Chinese...
  menu:
    main:
      - name: Members
        url: people
        weight: 10
      - name: Our Events
        url: event
        weight: 20
      - name: Agenda
        url: /#agenda
        weight: 30
      - name: Conferences
        url: confs
        weight: 40
      - name: Publications
        url: publication
        weight: 50
      - name: Contact
        url: /#homecontact
        weight: 60
